In [3]:
element = 'oxygen'
print('first three character:', element[0:3])
print('last three characters:', element[3:6])

first three character: oxy
last three characters: gen


In [12]:
element[:4]
#element[:4] will give an output of character starting from the first index to the fourth index

'oxyg'

In [13]:
element[4:]
#element[4:] will give an output of characters starting from the 4th index to the last index

'en'

In [14]:
element[:]
#element[:] will give an output of all characters

'oxygen'

In [7]:
element[-1]
#element [-1] will give an output of the last character

'n'

In [8]:
element[-2]
#element [-2] will give an output of the second to last character

'e'

In [9]:
element[1:-1]
#element[1:-1] will give you the 1st index which is the second character "x" and all the characters until and excluding the last character "n"

'xyge'

In [15]:
element[3:3]
#data[3:3, 4:4] will produce an empty array as well since it's calling the 3rd to the 3rd index and 4th to the 4th index which is equivalent to (0,0)
#data[3:3, ; ] will produce an empty array as well and it will call the 3rd to 3rd index and all the indexs

''

In [19]:
import numpy

A=numpy.array([[1,2,3], [4,5,6], [7,8,9]])
print('A = ')
print(A)

B=numpy.hstack([A,A])
print('B = ')
print(B)

C=numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
A2=A[0:, 0:3:2]
A3=numpy.hstack([A2,A2,A2])
D=numpy.vstack([A3,A3])
print('D = ')
print(D)

D = 
[[1 3 1 3 1 3]
 [4 6 4 6 4 6]
 [7 9 7 9 7 9]
 [1 3 1 3 1 3]
 [4 6 4 6 4 6]
 [7 9 7 9 7 9]]


In [92]:
npdiff=numpy.array([ 0, 2, 5, 9, 14])
print(npdiff)

[ 0  2  5  9 14]


In [93]:
numpy.diff[npdiff]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:
# 1) It would make sense to use this function along axis=1 when analyzing the inflamation data since each column is a different day of data for a single individual. 

# 2) The shape of the array after running the diff() function for a data file that is (60, 40) would be (60,39) if ran according to axis=1 and (59,40) if ran according to axis=0. When diff is ran it takes the first value and subtract the next value with it and this goes on until the second to last value, and not the last value since the last value does not have a proceeding number to subtract from. There will always be one less row or column for the array after the diff() is applied.

# 3) Using the function max() and abs() you can find the largest change regardless if it is an increase or decrease in value. You can also find it for each patient by specifying axis=0 when using the diff() function.

array([2])