In [3]:
import numpy

In [4]:
import numpy as np

In [14]:
inflam_data = numpy.loadtxt(fname="inflammation-01.csv", delimiter=',')
print(inflam_data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


In [40]:
for x in range(40):
    patientstd=np.std(inflam_data[:,x])
    print(patientstd)


0.0
0.4714045207910317
0.4714045207910317
0.9428090415820634
0.816496580927726
0.4714045207910317
1.247219128924647
2.357022603955158
2.449489742783178
2.449489742783178
2.943920288775949
3.265986323710904
2.6246692913372702
1.8856180831641267
1.4142135623730951
5.1854497287013475
0.9428090415820632
3.6817870057290873
1.699673171197595
4.988876515698588
5.9066817155564495
4.496912521077347
0.4714045207910316
4.898979485566356
2.357022603955158
2.357022603955158
3.2998316455372225
0.816496580927726
2.867441755680875
2.6246692913372702
3.091206165165234
0.4714045207910317
0.4714045207910317
2.0548046676563256
1.247219128924647
0.816496580927726
0.4714045207910317
0.816496580927726
0.4714045207910317
0.4714045207910317


IndexError: index 41 is out of bounds for axis 1 with size 40